language:
   - java

jdk:
   - oraclejdk8

install:
   - wget https://github.com/redpen-cc/redpen/releases/download/redpen-1.6.2/redpen-1.6.2.tar.gz && tar xvf redpen-1.6.2.tar.gz
   - export PATH=$PATH:$PWD/redpen-distribution-1.6.2/bin
   - function t() { redpen -c redpen-conf.xml -f latex $@ -l 0; };
   - function f() { redpen -c redpen-conf.xml -f latex $@ -l 0; if [ $? = 1 ]; then return 0; else return 1; fi };

script:
   - t main.tex
   ##### RULE 01 記号に関する規約 #####
   # 句読点
   - t tex/rule1-pos1.tex
   - t tex/rule1-pos2.tex
   - f tex/rule1-neg1.tex
   - f tex/rule1-neg2.tex
   - f tex/rule1-neg3.tex
   - f tex/rule1-neg4.tex
   # コロン
   - t tex/rule1-pos3.tex
   - f tex/rule1-neg5.tex
   - f tex/rule1-neg6.tex
   # セミコロン
   - t tex/rule1-pos4.tex
   - f tex/rule1-neg7.tex
   - f tex/rule1-neg8.tex
   # クエスチョンマーク
   - t tex/rule1-pos5.tex
   - f tex/rule1-neg9.tex
   # エクステンションマーク
   - t tex/rule1-pos6.tex
   - f tex/rule1-neg10.tex
   # スペース
   - t tex/rule1-pos7.tex
   - f tex/rule1-neg11.tex
   # ダブルコーテーション
   # - t tex/rule1-pos8.tex
   # - t tex/rule1-neg12.tex
   ##### RULE 02 文長に関する規約 #####
   # 文長
   - t tex/rule2-pos1.tex
   - f tex/rule2-neg1.tex
   # コンマ数
   - t tex/rule2-pos2.tex
   - f tex/rule2-neg2.tex
   ##### RULE 03 日本語表現に関する規約 #####
   # 数値表現の統一
   - t tex/rule3-pos1.tex
   - f tex/rule3-neg1.tex
   # カタカナ単語のゆらぎ
   - t tex/rule3-pos2.tex tex/rule3-pos3.tex
   - f tex/rule3-neg2.tex tex/rule3-neg3.tex
   # 同じ文頭表現を過度に使わない
   - t tex/rule3-pos4.tex
   - f tex/rule3-neg4.tex
   # 「の」を過度に連続して使わない
   - t tex/rule3-pos5.tex
   - f tex/rule3-neg5.tex
   # カタカナ単語の語尾を適切にする
   - t tex/rule3-pos6.tex
   - f tex/rule3-neg6.tex
   # 漢字の連続は5文字まで
   - t tex/rule3-pos7.tex
   - f tex/rule3-neg7.tex
   # 二重否定を使わない
   - t tex/rule3-pos8.tex
   - f tex/rule3-neg8.tex
   # 二重否定を使わない
   - t tex/rule3-pos9.tex
   - f tex/rule3-neg9.tex
   # 漢字かひらがなか、送り仮名
   - t tex/rule3-pos10.tex
   - f tex/rule3-neg10.tex
   ##### RULE04 翻訳特有の規約 #####
   #TODO: cannot use both java and python 
   # - exit_with_zero python script/validate_terms.py resources/term-dic.tsv tex/rule4-pos1.tex #TODO: implement exit_with_zero 
   # - exit_with_one python script/validate_terms.py resources/term-dic.tsv tex/rule4-neg1.tex #TODO: implement exit_with_one
   # 不適切な訳語を使わない
   - t tex/rule4-pos2.tex
   - f tex/rule4-neg2.tex
   # 文字修飾を原文に統一する
   # - python script/validate_modifier.py resources/modifier.txt tex/rule4-pos3.tex
   # - python script/validate_modifier.py resources/modifier.txt tex/rule4-neg3.tex
