language:
   - java

jdk:
   - oraclejdk8

install:
   - wget https://github.com/redpen-cc/redpen/releases/download/redpen-1.6.2/redpen-1.6.2.tar.gz && tar xvf redpen-1.6.2.tar.gz
   - export PATH=$PATH:$PWD/redpen-distribution-1.6.2/bin
   - function t() { redpen -c redpen-conf.xml -f latex $@ -l 0; };
   - function f() { redpen -c redpen-conf.xml -f latex $@ -l 0; if [ $? = 1 ]; then return 0; else return 1; fi };

script:
   - t main.tex
   ##### RULE 01 記号に関する規約 #####
   # 句読点
   - t tex/rule1-pos1.tex
   - t tex/rule1-pos2.tex
   - f tex/rule1-neg1.tex
   - f tex/rule1-neg2.tex
   - f tex/rule1-neg3.tex
   - f tex/rule1-neg4.tex
   # コロン
   - t tex/rule1-pos3.tex
   - f tex/rule1-neg5.tex
   - f tex/rule1-neg6.tex
   # セミコロン
   - t tex/rule1-pos4.tex
   - f tex/rule1-neg7.tex
   - f tex/rule1-neg8.tex
   # クエスチョンマーク
   - t tex/rule1-pos5.tex
   - f tex/rule1-neg9.tex
   # エクステンションマーク
   - t tex/rule1-pos6.tex
   - f tex/rule1-neg10.tex
   # スペース
   - t tex/rule1-pos7.tex
   - f tex/rule1-neg11.tex
   ##### RULE 02 文長に関する規約 #####
   # 文長
   - t tex/rule2-pos1.tex
   - f tex/rule2-neg1.tex
   # コンマ数
   - t tex/rule2-pos2.tex
   - f tex/rule2-neg2.tex
